mexc:
  # WebSocket Spot V3 endpoint
  ws_url: wss://wbs.mexc.com/ws
  rest_url: https://api.mexc.com
  api_key: ${MEXC_KEY}
  api_secret: ${MEXC_SECRET}
scanner:
  stake_usdt: ${STAKE_USDT}
  prob_threshold: ${PROB_THRESHOLD}
  metrics:
    vsr: ${THRESH_VSR}
    pm: ${THRESH_PM}
    obi: ${THRESH_OBI}
    spread: ${THRESH_SPREAD}
    listing_age_min: ${THRESH_LISTING_AGE}
telegram:
  token: ${TG_TOKEN}
  allowed_ids: [${ALLOWED_IDS}]
scout:
  min_quote_vol_usd: 100000
  top_n: 200
ws:
  max_streams_per_conn: 30
  max_msg_per_sec: 100
